<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="TUnit" Version="1.44.39" />
    <PackageVersion Include="TUnit.Core" Version="1.56.35" />
    <PackageVersion Include="TUnit.Assertions" Version="1.56.18" />
  </ItemGroup>

</Project>
