name: Build & Pack

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            10.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore src/NVMathNet/NVMathNet.csproj

      # Tests require NVIDIA GPU
      #- name: Test
      #  run: dotnet test -c Release --no-build

      - name: Pack
        run: dotnet pack -c Release --no-build -o nupkgs src/NVMathNet/NVMathNet.csproj

      - name: Upload package
        uses: actions/upload-artifact@v7
        with:
          name: nuget-package
          path: nupkgs/*.nupkg
